<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>learnluxembourgish-api-secrets</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DeepL.net" Version="1.19.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
    <PackageReference Include="Microsoft.Identity.Web" Version="4.4.0" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.72.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LearnLuxembourgish.Data.Shared\LearnLuxembourgish.Data.Shared.csproj" />
    <ProjectReference Include="..\LearnLuxembourgish.Data.SQLite\LearnLuxembourgish.Data.SQLite.csproj" />
    <ProjectReference Include="..\LearnLuxembourgish.Shared\LearnLuxembourgish.Shared.csproj" />
    <ProjectReference Include="..\LearnLuxembourgish.ServiceDefaults\LearnLuxembourgish.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
