using System.Security.Cryptography;
using System.Text;
using LearnLuxembourgish.Data.Shared;
using LearnLuxembourgish.Data.Shared.Entities;
using LearnLuxembourgish.Shared.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LearnLuxembourgish.Api.Controllers;

[ApiController]
[Route("api/[controller]")]
public class AudioController : ControllerBase
{
    private readonly LearnLuxembourgishDbContext _dbContext;
    private readonly ILogger<AudioController> _logger;

    public AudioController(LearnLuxembourgishDbContext dbContext, ILogger<AudioController> logger)
    {
        _dbContext = dbContext;
        _logger = logger;
    }

    /// <summary>
    /// Returns cached audio for a given ID.
    /// </summary>
    [HttpGet("{id:guid}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> GetAudio(Guid id, CancellationToken cancellationToken)
    {
        var audio = await _dbContext.TranslationAudios.FindAsync([id], cancellationToken);
        if (audio is null)
            return NotFound();

        return File(audio.AudioData, audio.ContentType);
    }

    /// <summary>
    /// Accepts audio generated by the client and caches it for reuse.
    /// If audio for the same Luxembourgish text already exists, the existing entry is returned.
    /// </summary>
    [HttpPost]
    [ProducesResponseType(typeof(AudioUploadResult), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<ActionResult<AudioUploadResult>> UploadAudio(
        [FromBody] AudioUploadRequest request,
        CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(request.LuxembourgishText))
            return BadRequest("LuxembourgishText is required.");

        if (string.IsNullOrWhiteSpace(request.AudioData))
            return BadRequest("AudioData is required.");

        byte[] audioBytes;
        try
        {
            audioBytes = Convert.FromBase64String(request.AudioData);
        }
        catch (FormatException)
        {
            return BadRequest("AudioData must be a valid base-64 string.");
        }

        var hash = ComputeTextHash(request.LuxembourgishText);

        var existing = await _dbContext.TranslationAudios
            .FirstOrDefaultAsync(a => a.TextHash == hash, cancellationToken);

        if (existing is not null)
        {
            _logger.LogInformation("Audio cache hit for text hash {Hash}", hash);
            return Ok(new AudioUploadResult { AudioUrl = $"api/audio/{existing.Id}" });
        }

        var contentType = string.IsNullOrWhiteSpace(request.ContentType) ? "audio/wav" : request.ContentType;

        var audio = new TranslationAudio
        {
            LuxembourgishText = request.LuxembourgishText,
            TextHash = hash,
            AudioData = audioBytes,
            ContentType = contentType
        };

        _dbContext.TranslationAudios.Add(audio);
        await _dbContext.SaveChangesAsync(cancellationToken);

        _logger.LogInformation("Audio cached for text length {Length}, id {AudioId}", request.LuxembourgishText.Length, audio.Id);
        return Ok(new AudioUploadResult { AudioUrl = $"api/audio/{audio.Id}" });
    }

    internal static string ComputeTextHash(string text)
    {
        var normalized = text.Trim().ToLowerInvariant();
        var bytes = SHA256.HashData(Encoding.UTF8.GetBytes(normalized));
        return Convert.ToHexString(bytes).ToLowerInvariant();
    }
}
